### ISSUE TITLE
Patch version of ecto is pinned

### ISSUE THREAD

**Issue by mbuhot** [Sqlite-Ecto/sqlite_ecto2#223]
Hello, thanks for creating this package 👍 

I noticed the patch version for the ecto dependency got pinned in [this commit](https://github.com/Sqlite-Ecto/sqlite_ecto2/commit/e14241a53d8cb083f46b69febe2b279d02d29c69#diff-6023be6004fce4718dad3dafb576d258L46) from `~> 2.2` to `2.2.9`

Are there incompatibilities with later 2.x ecto versions?

It's not a big deal to override the dependency, but it would be nice if I didn't need to.

**Comment by ConnorRigby** [comment]
I've pinned it because there technically are some things in 2.2.10 that this adapter doesn't support yet. I suppose i could revert that, but it may lead to undefined behavior. I can't remember off the top of my head what exactly was added, but for what it's worth I override the Ecto version and haven't had much issues. That said I dont use many advanced Ecto features

**Comment by mbuhot** [comment]
OK, thanks for clarifying.
